sites:
  snatches:
    name: "CodeSnatches Tutorials"
    url: "https://localhost/codesnatches/tutorials"
    form_selector: "#commentForm"
    username_field_selector: "#username_comm"
    content_field_selector: "#content_comm"
    challenge_field_selector: "#user_answer_for_sc"
    submit_button_selector: "input[name='page_comment_submit']"
    error_container_selector: ".main-message--error"
    success_container_selector: ".main-message--success"
    error_list_selector: "#formErrorList"
    success_message: "Your comment has been posted"
    

  services:
    name: "Services - About"
    url: "https://localhost/services/about"
    form_selector: "#commentForm"
    username_field_selector: "#username_comm"
    content_field_selector: "#content_comm"
    challenge_field_selector: "#user_answer_for_sc"
    submit_button_selector: "input[name='page_comment_submit']"
    error_container_selector: ".main-message--error"
    success_container_selector: ".main-message--success"
    error_list_selector: "#formErrorList"
    success_message: "Your comment has been posted"
    

  f-guitar:
    name: "f-guitar"
    url: "https://f-guitar.com/licks-4.html"
    form_selector: "#commentForm"
    username_field_selector: "#username_comm"
    content_field_selector: "#content_comm"
    challenge_field_selector: "#user_answer_for_sc"
    submit_button_selector: "input[name='page_comment_submit']"
    error_container_selector: ".main-message--error"
    success_container_selector: ".main-message--success"
    error_list_selector: "#formErrorList"
    success_message: "Your comment has been posted"
