name: Run Behave Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y xvfb    

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        playwright install chromium
    
    - name: Run Behave tests
      # run: xvfb-run  behave  # xvfb-run provides virtual display for GitHub Actions.
      run: xvfb-run  behave -D site=f-guitar --tags smoke  # xvfb-run provides virtual display for GitHub Actions.
      
